### ISSUE TITLE
Effect of gaussian smoothing

### ISSUE THREAD

**Issue by derkbreeze** [orhir/STG-NF#21]
Hi Or,

The work is very inspiring!

I have tested the checkpoints on ShanghaiTech dataset, I found that without gaussian smoothing the model can only achieve 81.9 AUC but after smoothing it achieved 85.9 AUC as reported. Why does the smoothing/postprocessing gives so much performance gain?

Thanks

**Comment by orhir** [comment]
Thank you for showing interest in our work.
The extracted pose sequences, as well as the output scores, are sometimes noisy (due to bad tracking, pose estimation, etc.).
The post-processing smoothing makes sure the output scores are temporal consistent.
It is reasonable to assume that adjacent frames will have similar scores, thus the smoothing helps.

**Comment by derkbreeze** [comment]
Thanks!
